In [1]:
!pip install fastf1

Defaulting to user installation because normal site-packages is not writeable
Collecting fastf1
  Downloading fastf1-3.6.0-py3-none-any.whl (148 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 148.4/148.4 KB 3.2 MB/s eta 0:00:00a 0:00:01
Collecting numpy<3.0.0,>=1.23.1
  Downloading numpy-2.2.6-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.8/16.8 MB 54.7 MB/s eta 0:00:0000:0100:01
Collecting scipy<2.0.0,>=1.8.1
  Downloading scipy-1.15.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (37.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 37.7/37.7 MB 26.2 MB/s eta 0:00:0000:0100:01
Collecting requests>=2.28.1
  Downloading requests-2.32.4-py3-none-any.whl (64 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.8/64.8 KB 11.8 MB/s eta 0:00:00
Requirement already satisfied: python-dateutil in /workspace/.pyenv_mirror/user/current/lib/python3.10/site-packages (from fastf1) (2.9.0.post0)
Collecting timple>=0.1.6
  Downloading timple-0.1.8-py3-none-any.whl (17 kB)
Collecting pandas<3.0.0,>=1.4.1
  Downloading pandas-2.3.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.3/12.3 MB 84.8 MB/s eta 0:00:0000:0100:01
Collecting websockets<14,>=10.3
  Downloading websockets-13.1-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (164 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 164.1/164.1 KB 35.3 MB/s eta 0:00:00
Collecting matplotlib<4.0.0,>=3.5.1
  Downloading matplotlib-3.10.5-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (8.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.7/8.7 MB 90.6 MB/s eta 0:00:00:00:0100:01
Collecting requests-cache>=1.0.0
  Downloading requests_cache-1.2.1-py3-none-any.whl (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.4/61.4 KB 11.8 MB/s eta 0:00:00
Collecting rapidfuzz
  Downloading rapidfuzz-3.13.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 71.7 MB/s eta 0:00:00:00:01
Collecting contourpy>=1.0.1
  Downloading contourpy-1.3.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (325 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 325.0/325.0 KB 42.8 MB/s eta 0:00:00
Requirement already satisfied: pyparsing>=2.3.1 in /usr/lib/python3/dist-packages (from matplotlib<4.0.0,>=3.5.1->fastf1) (2.4.7)
Requirement already satisfied: packaging>=20.0 in /workspace/.pyenv_mirror/user/current/lib/python3.10/site-packages (from matplotlib<4.0.0,>=3.5.1->fastf1) (25.0)
Collecting pillow>=8
  Downloading pillow-11.3.0-cp310-cp310-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (6.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.6/6.6 MB 100.9 MB/s eta 0:00:0000:01
Collecting kiwisolver>=1.3.1
  Downloading kiwisolver-1.4.9-cp310-cp310-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 91.2 MB/s eta 0:00:00
Collecting fonttools>=4.22.0
  Downloading fonttools-4.59.0-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.8/4.8 MB 105.6 MB/s eta 0:00:0000:01
Collecting cycler>=0.10
  Downloading cycler-0.12.1-py3-none-any.whl (8.3 kB)
Collecting tzdata>=2022.7
  Downloading tzdata-2025.2-py2.py3-none-any.whl (347 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 347.8/347.8 KB 79.1 MB/s eta 0:00:00
Collecting pytz>=2020.1
  Downloading pytz-2025.2-py2.py3-none-any.whl (509 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 509.2/509.2 KB 88.3 MB/s eta 0:00:00
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil->fastf1) (1.16.0)
Collecting certifi>=2017.4.17
  Downloading certifi-2025.8.3-py3-none-any.whl (161 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 161.2/161.2 KB 43.3 MB/s eta 0:00:00
Collecting idna<4,>=2.5
  Downloading idna-3.10-py3-none-any.whl (70 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.4/70.4 KB 26.9 MB/s eta 0:00:00
Collecting urllib3<3,>=1.21.1
  Downloading urllib3-2.5.0-py3-none-any.whl (129 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.8/129.8 KB 47.5 MB/s eta 0:00:00
Collecting charset_normalizer<4,>=2
  Downloading charset_normalizer-3.4.3-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (152 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 152.4/152.4 KB 46.8 MB/s eta 0:00:00
Requirement already satisfied: platformdirs>=2.5 in /workspace/.pyenv_mirror/user/current/lib/python3.10/site-packages (from requests-cache>=1.0.0->fastf1) (4.3.8)
Collecting cattrs>=22.2
  Downloading cattrs-25.1.1-py3-none-any.whl (69 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.4/69.4 KB 30.9 MB/s eta 0:00:00
Collecting url-normalize>=1.4
  Downloading url_normalize-2.2.1-py3-none-any.whl (14 kB)
Collecting attrs>=21.2
  Downloading attrs-25.3.0-py3-none-any.whl (63 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.8/63.8 KB 27.4 MB/s eta 0:00:00
Requirement already satisfied: exceptiongroup>=1.1.1 in /workspace/.pyenv_mirror/user/current/lib/python3.10/site-packages (from cattrs>=22.2->requests-cache>=1.0.0->fastf1) (1.3.0)
Requirement already satisfied: typing-extensions>=4.12.2 in /workspace/.pyenv_mirror/user/current/lib/python3.10/site-packages (from cattrs>=22.2->requests-cache>=1.0.0->fastf1) (4.14.1)
Installing collected packages: pytz, websockets, urllib3, tzdata, rapidfuzz, pillow, numpy, kiwisolver, idna, fonttools, cycler, charset_normalizer, certifi, attrs, url-normalize, scipy, requests, pandas, contourpy, cattrs, requests-cache, matplotlib, timple, fastf1
Successfully installed attrs-25.3.0 cattrs-25.1.1 certifi-2025.8.3 charset_normalizer-3.4.3 contourpy-1.3.2 cycler-0.12.1 fastf1-3.6.0 fonttools-4.59.0 idna-3.10 kiwisolver-1.4.9 matplotlib-3.10.5 numpy-2.2.6 pandas-2.3.1 pillow-11.3.0 pytz-2025.2 rapidfuzz-3.13.0 requests-2.32.4 requests-cache-1.2.1 scipy-1.15.3 timple-0.1.8 tzdata-2025.2 url-normalize-2.2.1 urllib3-2.5.0 websockets-13.1

In [2]:
import json
import os

import fastf1
import numpy as np
import pandas as pd

import utils

fastf1.Cache.enable_cache("cache")
YEAR = 2025

In [12]:
session = fastf1.get_session(2025, 'Chinese Grand Prix', 'SQ')

session.load()

core           INFO 	Loading data for Chinese Grand Prix - Sprint Qualifying [v3.6.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
core        WARNING 	Sprint Qualifying is not supported by Ergast! Limited results are calculated from timing data.
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '1', '81', '16', '63', '4', '12', '22', '23', '18', '14', '87', '55', '5', '6', '7', '10', '31', '27', '30']

In [13]:
laps = session.laps
laps

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
0,0 days 00:16:57.349000,NOR,4,NaT,1.0,1.0,0 days 00:14:48.482000,NaT,NaT,0 days 00:00:35.498000,...,True,McLaren,0 days 00:14:48.482000,2025-03-21 07:32:20.802,1,NaN,False,,False,False
1,0 days 00:18:29.597000,NOR,4,0 days 00:01:32.248000,2.0,1.0,NaT,NaT,0 days 00:00:24.618000,0 days 00:00:27.789000,...,True,McLaren,0 days 00:16:57.349000,2025-03-21 07:34:29.669,1,NaN,False,,False,True
2,0 days 00:20:32.738000,NOR,4,0 days 00:02:03.141000,3.0,1.0,NaT,NaT,0 days 00:00:34.193000,0 days 00:00:38.202000,...,True,McLaren,0 days 00:18:29.597000,2025-03-21 07:36:01.917,1,NaN,False,,False,True
3,0 days 00:22:38.639000,NOR,4,0 days 00:02:05.901000,4.0,1.0,NaT,NaT,0 days 00:00:38.528000,0 days 00:00:35.518000,...,True,McLaren,0 days 00:20:32.738000,2025-03-21 07:38:05.058,1,NaN,False,,False,True
4,0 days 00:24:10.035000,NOR,4,0 days 00:01:31.396000,5.0,1.0,NaT,NaT,0 days 00:00:24.207000,0 days 00:00:27.555000,...,True,McLaren,0 days 00:22:38.639000,2025-03-21 07:40:10.959,1,NaN,False,,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
212,0 days 00:17:06.350000,DOO,7,0 days 00:01:33.129000,2.0,1.0,NaT,NaT,0 days 00:00:24.791000,0 days 00:00:28.114000,...,True,Alpine,0 days 00:15:33.221000,2025-03-21 07:33:05.541,1,NaN,False,,False,True
213,0 days 00:19:08.929000,DOO,7,0 days 00:02:02.579000,3.0,1.0,NaT,NaT,0 days 00:00:31.130000,0 days 00:00:37.759000,...,True,Alpine,0 days 00:17:06.350000,2025-03-21 07:34:38.670,1,NaN,False,,False,True
214,0 days 00:21:15.101000,DOO,7,0 days 00:02:06.172000,4.0,1.0,NaT,NaT,0 days 00:00:33.351000,0 days 00:00:37.366000,...,True,Alpine,0 days 00:19:08.929000,2025-03-21 07:36:41.249,1,NaN,False,,False,True
215,0 days 00:22:47.676000,DOO,7,0 days 00:01:32.575000,5.0,1.0,NaT,NaT,0 days 00:00:24.609000,0 days 00:00:27.945000,...,True,Alpine,0 days 00:21:15.101000,2025-03-21 07:38:47.421,1,NaN,False,,False,True
216,0 days 00:24:48.969000,DOO,7,0 days 00:02:01.293000,6.0,1.0,NaT,0 days 00:24:46.841000,0 days 00:00:33.434000,0 days 00:00:35.993000,...,True,Alpine,0 days 00:22:47.676000,2025-03-21 07:40:19.996,1,NaN,False,,False,False

In [14]:
q1, q2, q3 = laps.split_qualifying_sessions()
q1
print("Above is q1")
q2
print("Above is q2")
q3
print("Above is q3")

Above is q1
Above is q2
Above is q3

In [15]:
q1

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
0,0 days 00:16:57.349000,NOR,4,NaT,1.0,1.0,0 days 00:14:48.482000,NaT,NaT,0 days 00:00:35.498000,...,True,McLaren,0 days 00:14:48.482000,2025-03-21 07:32:20.802,1,NaN,False,,False,False
1,0 days 00:18:29.597000,NOR,4,0 days 00:01:32.248000,2.0,1.0,NaT,NaT,0 days 00:00:24.618000,0 days 00:00:27.789000,...,True,McLaren,0 days 00:16:57.349000,2025-03-21 07:34:29.669,1,NaN,False,,False,True
2,0 days 00:20:32.738000,NOR,4,0 days 00:02:03.141000,3.0,1.0,NaT,NaT,0 days 00:00:34.193000,0 days 00:00:38.202000,...,True,McLaren,0 days 00:18:29.597000,2025-03-21 07:36:01.917,1,NaN,False,,False,True
3,0 days 00:22:38.639000,NOR,4,0 days 00:02:05.901000,4.0,1.0,NaT,NaT,0 days 00:00:38.528000,0 days 00:00:35.518000,...,True,McLaren,0 days 00:20:32.738000,2025-03-21 07:38:05.058,1,NaN,False,,False,True
4,0 days 00:24:10.035000,NOR,4,0 days 00:01:31.396000,5.0,1.0,NaT,NaT,0 days 00:00:24.207000,0 days 00:00:27.555000,...,True,McLaren,0 days 00:22:38.639000,2025-03-21 07:40:10.959,1,NaN,False,,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
212,0 days 00:17:06.350000,DOO,7,0 days 00:01:33.129000,2.0,1.0,NaT,NaT,0 days 00:00:24.791000,0 days 00:00:28.114000,...,True,Alpine,0 days 00:15:33.221000,2025-03-21 07:33:05.541,1,NaN,False,,False,True
213,0 days 00:19:08.929000,DOO,7,0 days 00:02:02.579000,3.0,1.0,NaT,NaT,0 days 00:00:31.130000,0 days 00:00:37.759000,...,True,Alpine,0 days 00:17:06.350000,2025-03-21 07:34:38.670,1,NaN,False,,False,True
214,0 days 00:21:15.101000,DOO,7,0 days 00:02:06.172000,4.0,1.0,NaT,NaT,0 days 00:00:33.351000,0 days 00:00:37.366000,...,True,Alpine,0 days 00:19:08.929000,2025-03-21 07:36:41.249,1,NaN,False,,False,True
215,0 days 00:22:47.676000,DOO,7,0 days 00:01:32.575000,5.0,1.0,NaT,NaT,0 days 00:00:24.609000,0 days 00:00:27.945000,...,True,Alpine,0 days 00:21:15.101000,2025-03-21 07:38:47.421,1,NaN,False,,False,True
216,0 days 00:24:48.969000,DOO,7,0 days 00:02:01.293000,6.0,1.0,NaT,0 days 00:24:46.841000,0 days 00:00:33.434000,0 days 00:00:35.993000,...,True,Alpine,0 days 00:22:47.676000,2025-03-21 07:40:19.996,1,NaN,False,,False,False

In [17]:
q2

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
6,0 days 00:33:56.277000,NOR,4,NaT,7.0,2.0,0 days 00:32:03.140000,NaT,NaT,0 days 00:00:31.673000,...,True,McLaren,0 days 00:26:16.460000,2025-03-21 07:43:48.780,12,NaN,False,,False,False
7,0 days 00:35:27.451000,NOR,4,0 days 00:01:31.174000,8.0,2.0,NaT,NaT,0 days 00:00:24.278000,0 days 00:00:27.499000,...,True,McLaren,0 days 00:33:56.277000,2025-03-21 07:51:28.597,1,NaN,False,,False,True
8,0 days 00:37:34.240000,NOR,4,0 days 00:02:06.789000,9.0,2.0,NaT,0 days 00:37:32.458000,0 days 00:00:31.850000,0 days 00:00:37.808000,...,True,McLaren,0 days 00:35:27.451000,2025-03-21 07:52:59.771,1,NaN,False,,False,False
19,0 days 00:34:24.347000,LEC,16,NaT,7.0,3.0,0 days 00:32:32.476000,NaT,NaT,0 days 00:00:33.832000,...,True,Ferrari,0 days 00:27:04.246000,2025-03-21 07:44:36.566,12,NaN,False,,False,False
20,0 days 00:36:22.873000,LEC,16,0 days 00:01:58.526000,8.0,3.0,NaT,NaT,0 days 00:00:24.561000,0 days 00:00:34.641000,...,True,Ferrari,0 days 00:34:24.347000,2025-03-21 07:51:56.667,1,NaN,False,,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206,0 days 00:35:40.034000,BOR,5,0 days 00:02:01.932000,8.0,3.0,NaT,NaT,0 days 00:00:25.743000,0 days 00:00:36.315000,...,True,Kick Sauber,0 days 00:33:38.102000,2025-03-21 07:51:10.422,1,NaN,False,,False,True
207,0 days 00:37:51.754000,BOR,5,0 days 00:02:11.720000,9.0,3.0,NaT,0 days 00:37:50.099000,0 days 00:00:35.415000,0 days 00:00:36.135000,...,True,Kick Sauber,0 days 00:35:40.034000,2025-03-21 07:53:12.354,1,NaN,False,,False,False
208,0 days 00:40:33.984000,BOR,5,NaT,10.0,4.0,0 days 00:38:38.183000,NaT,0 days 00:01:19.490000,0 days 00:00:32.688000,...,False,Kick Sauber,0 days 00:37:51.754000,2025-03-21 07:55:24.074,1,NaN,False,,False,False
209,0 days 00:42:06.548000,BOR,5,0 days 00:01:32.564000,11.0,4.0,NaT,NaT,0 days 00:00:24.852000,0 days 00:00:27.683000,...,False,Kick Sauber,0 days 00:40:33.984000,2025-03-21 07:58:06.304,1,NaN,False,,False,True
210,0 days 00:44:11.477000,BOR,5,0 days 00:02:04.929000,12.0,4.0,NaT,0 days 00:44:09.850000,0 days 00:00:36.059000,0 days 00:00:34.520000,...,False,Kick Sauber,0 days 00:42:06.548000,2025-03-21 07:59:38.868,12,NaN,False,,False,False

In [18]:
q3

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
9,0 days 00:50:44.735000,NOR,4,NaT,10.0,3.0,0 days 00:48:58.028000,NaT,NaT,0 days 00:00:31.965000,...,True,McLaren,0 days 00:37:34.240000,2025-03-21 07:55:06.560,12,NaN,False,,False,False
10,0 days 00:52:16.128000,NOR,4,0 days 00:01:31.393000,11.0,3.0,NaT,NaT,0 days 00:00:24.293000,0 days 00:00:27.440000,...,True,McLaren,0 days 00:50:44.735000,2025-03-21 08:08:17.055,1,NaN,False,,False,True
11,0 days 00:54:24.411000,NOR,4,0 days 00:02:08.283000,12.0,3.0,NaT,NaT,0 days 00:00:37.923000,0 days 00:00:39.061000,...,True,McLaren,0 days 00:52:16.128000,2025-03-21 08:09:48.448,1,NaN,False,,False,True
12,0 days 00:56:04.437000,NOR,4,0 days 00:01:40.026000,13.0,3.0,NaT,0 days 00:56:02.549000,0 days 00:00:24.009000,0 days 00:00:27.425000,...,True,McLaren,0 days 00:54:24.411000,2025-03-21 08:11:56.731,1,NaN,False,,False,False
25,0 days 00:54:09.359000,LEC,16,NaT,13.0,4.0,0 days 00:52:11.124000,NaT,NaT,0 days 00:00:35.264000,...,True,Ferrari,0 days 00:43:42.164000,2025-03-21 08:01:14.484,12,NaN,False,,False,False
26,0 days 00:55:40.416000,LEC,16,0 days 00:01:31.057000,14.0,4.0,NaT,NaT,0 days 00:00:24.322000,0 days 00:00:27.384000,...,True,Ferrari,0 days 00:54:09.359000,2025-03-21 08:11:41.679,1,NaN,False,,False,True
27,0 days 00:57:52.312000,LEC,16,0 days 00:02:11.896000,15.0,4.0,NaT,0 days 00:57:47.723000,0 days 00:00:30.642000,0 days 00:00:35.456000,...,True,Ferrari,0 days 00:55:40.416000,2025-03-21 08:13:12.736,1,NaN,False,,False,False
36,0 days 00:50:37.420000,PIA,81,NaT,9.0,3.0,0 days 00:48:47.231000,NaT,NaT,0 days 00:00:33.732000,...,True,McLaren,0 days 00:39:46.508000,2025-03-21 07:57:18.828,12,NaN,False,,False,False
37,0 days 00:52:08.349000,PIA,81,0 days 00:01:30.929000,10.0,3.0,NaT,NaT,0 days 00:00:24.297000,0 days 00:00:27.317000,...,True,McLaren,0 days 00:50:37.420000,2025-03-21 08:08:09.740,1,NaN,False,,False,True
38,0 days 00:54:18.856000,PIA,81,0 days 00:02:10.507000,11.0,3.0,NaT,NaT,0 days 00:00:39.544000,0 days 00:00:38.355000,...,True,McLaren,0 days 00:52:08.349000,2025-03-21 08:09:40.669,1,NaN,False,,False,True
39,0 days 00:55:49.796000,PIA,81,0 days 00:01:30.940000,12.0,3.0,NaT,NaT,0 days 00:00:24.248000,0 days 00:00:27.447000,...,True,McLaren,0 days 00:54:18.856000,2025-03-21 08:11:51.176,1,NaN,False,,False,True
40,0 days 00:57:57.309000,PIA,81,0 days 00:02:07.513000,13.0,3.0,NaT,0 days 00:57:53.957000,0 days 00:00:29.456000,0 days 00:00:37.735000,...,True,McLaren,0 days 00:55:49.796000,2025-03-21 08:13:22.116,1,NaN,False,,False,False
53,0 days 00:53:59.988000,HAM,44,NaT,13.0,4.0,0 days 00:52:02.764000,NaT,NaT,0 days 00:00:36.784000,...,True,Ferrari,0 days 00:43:37.415000,2025-03-21 08:01:09.735,12,NaN,False,,False,False
54,0 days 00:55:30.837000,HAM,44,0 days 00:01:30.849000,14.0,4.0,NaT,NaT,0 days 00:00:24.261000,0 days 00:00:27.249000,...,True,Ferrari,0 days 00:53:59.988000,2025-03-21 08:11:32.308,1,NaN,False,,False,True
55,0 days 00:57:46.118000,HAM,44,0 days 00:02:15.281000,15.0,4.0,NaT,0 days 00:57:41.512000,0 days 00:00:30.938000,0 days 00:00:36.019000,...,True,Ferrari,0 days 00:55:30.837000,2025-03-21 08:13:03.157,1,NaN,False,,False,False
71,0 days 00:50:59.491000,RUS,63,NaT,16.0,3.0,0 days 00:49:15.622000,NaT,NaT,0 days 00:00:30.529000,...,True,Mercedes,0 days 00:44:44.454000,2025-03-21 08:02:16.774,21,NaN,False,,False,False
72,0 days 00:52:30.660000,RUS,63,0 days 00:01:31.169000,17.0,3.0,NaT,NaT,0 days 00:00:24.302000,0 days 00:00:27.425000,...,True,Mercedes,0 days 00:50:59.491000,2025-03-21 08:08:31.811,1,NaN,False,,False,True
73,0 days 00:54:40.639000,RUS,63,0 days 00:02:09.979000,18.0,3.0,NaT,0 days 00:54:38.899000,0 days 00:00:34.461000,0 days 00:00:37.688000,...,True,Mercedes,0 days 00:52:30.660000,2025-03-21 08:10:02.980,1,NaN,False,,False,False
90,0 days 00:53:53.111000,ALB,23,NaT,11.0,3.0,0 days 00:51:53.358000,NaT,NaT,0 days 00:00:37.658000,...,True,Williams,0 days 00:44:17.175000,2025-03-21 08:01:49.495,21,NaN,False,,False,False
91,0 days 00:55:45.314000,ALB,23,0 days 00:01:52.203000,12.0,3.0,NaT,NaT,0 days 00:00:28.463000,0 days 00:00:35.900000,...,True,Williams,0 days 00:53:53.111000,2025-03-21 08:11:25.431,1,NaN,False,,False,True
92,0 days 00:57:17.166000,ALB,23,0 days 00:01:31.852000,13.0,3.0,NaT,NaT,0 days 00:00:24.415000,0 days 00:00:27.702000,...,True,Williams,0 days 00:55:45.314000,2025-03-21 08:13:17.634,1,NaN,False,,False,True
93,0 days 00:59:23.413000,ALB,23,0 days 00:02:06.247000,14.0,3.0,NaT,0 days 00:59:20.405000,0 days 00:00:30.970000,0 days 00:00:38.407000,...,True,Williams,0 days 00:57:17.166000,2025-03-21 08:14:49.486,1,NaN,False,,False,False
116,0 days 00:50:52.456000,ANT,12,NaT,15.0,4.0,0 days 00:49:04.013000,NaT,NaT,0 days 00:00:32.340000,...,True,Mercedes,0 days 00:44:40.462000,2025-03-21 08:02:12.782,21,NaN,False,,False,False
117,0 days 00:52:24.194000,ANT,12,0 days 00:01:31.738000,16.0,4.0,NaT,NaT,0 days 00:00:24.582000,0 days 00:00:27.652000,...,True,Mercedes,0 days 00:50:52.456000,2025-03-21 08:08:24.776,1,NaN,False,,False,True
118,0 days 00:54:37.938000,ANT,12,0 days 00:02:13.744000,17.0,4.0,NaT,0 days 00:54:36.067000,0 days 00:00:35.044000,0 days 00:00:38.855000,...,True,Mercedes,0 days 00:52:24.194000,2025-03-21 08:09:56.514,1,NaN,False,,False,False
128,0 days 00:56:04.551000,TSU,22,NaT,10.0,4.0,0 days 00:54:05.035000,NaT,NaT,0 days 00:00:38.351000,...,True,Racing Bulls,0 days 00:43:27.101000,2025-03-21 08:00:59.421,12,NaN,False,,False,False
129,0 days 00:57:36.324000,TSU,22,0 days 00:01:31.773000,11.0,4.0,NaT,NaT,0 days 00:00:24.350000,0 days 00:00:27.627000,...,True,Racing Bulls,0 days 00:56:04.551000,2025-03-21 08:13:36.871,1,NaN,False,,False,True
130,0 days 00:59:46.620000,TSU,22,0 days 00:02:10.296000,12.0,4.0,NaT,0 days 00:59:42.278000,0 days 00:00:32.866000,0 days 00:00:36.134000,...,True,Racing Bulls,0 days 00:57:36.324000,2025-03-21 08:15:08.644,1,NaN,False,,False,False
149,0 days 00:54:29.913000,STR,18,NaT,10.0,3.0,0 days 00:52:14.580000,NaT,NaT,0 days 00:00:38.712000,...,False,Aston Martin,0 days 00:43:34.914000,2025-03-21 08:01:07.234,12,NaN,False,,False,False
150,0 days 00:56:01.895000,STR,18,0 days 00:01:31.982000,11.0,3.0,NaT,NaT,0 days 00:00:24.231000,0 days 00:00:27.771000,...,False,Aston Martin,0 days 00:54:29.913000,2025-03-21 08:12:02.233,1,NaN,False,,False,True
151,0 days 00:58:11.210000,STR,18,0 days 00:02:09.315000,12.0,3.0,NaT,0 days 00:58:06.998000,0 days 00:00:31.937000,0 days 00:00:33.332000,...,False,Aston Martin,0 days 00:56:01.895000,2025-03-21 08:13:34.215,1,NaN,False,,False,False
183,0 days 00:55:26.460000,VER,1,NaT,10.0,4.0,0 days 00:53:25.966000,NaT,NaT,0 days 00:00:37.234000,...,True,Red Bull Racing,0 days 00:37:30.920000,2025-03-21 07:55:03.240,12,NaN,False,,False,False
184,0 days 00:56:57.327000,VER,1,0 days 00:01:30.867000,11.0,4.0,NaT,NaT,0 days 00:00:24.269000,0 days 00:00:27.361000,...,True,Red Bull Racing,0 days 00:55:26.460000,2025-03-21 08:12:58.780,1,NaN,False,,False,True
185,0 days 00:59:08.838000,VER,1,0 days 00:02:11.511000,12.0,4.0,NaT,0 days 00:59:06.275000,0 days 00:00:34.047000,0 days 00:00:38.713000,...,True,Red Bull Racing,0 days 00:56:57.327000,2025-03-21 08:14:29.647,1,NaN,False,,False,False

In [19]:
q3.columns

Index(['Time', 'Driver', 'DriverNumber', 'LapTime', 'LapNumber', 'Stint',
       'PitOutTime', 'PitInTime', 'Sector1Time', 'Sector2Time', 'Sector3Time',
       'Sector1SessionTime', 'Sector2SessionTime', 'Sector3SessionTime',
       'SpeedI1', 'SpeedI2', 'SpeedFL', 'SpeedST', 'IsPersonalBest',
       'Compound', 'TyreLife', 'FreshTyre', 'Team', 'LapStartTime',
       'LapStartDate', 'TrackStatus', 'Position', 'Deleted', 'DeletedReason',
       'FastF1Generated', 'IsAccurate'],
      dtype='object')

In [16]:
laps

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
0,0 days 00:16:57.349000,NOR,4,NaT,1.0,1.0,0 days 00:14:48.482000,NaT,NaT,0 days 00:00:35.498000,...,True,McLaren,0 days 00:14:48.482000,2025-03-21 07:32:20.802,1,NaN,False,,False,False
1,0 days 00:18:29.597000,NOR,4,0 days 00:01:32.248000,2.0,1.0,NaT,NaT,0 days 00:00:24.618000,0 days 00:00:27.789000,...,True,McLaren,0 days 00:16:57.349000,2025-03-21 07:34:29.669,1,NaN,False,,False,True
2,0 days 00:20:32.738000,NOR,4,0 days 00:02:03.141000,3.0,1.0,NaT,NaT,0 days 00:00:34.193000,0 days 00:00:38.202000,...,True,McLaren,0 days 00:18:29.597000,2025-03-21 07:36:01.917,1,NaN,False,,False,True
3,0 days 00:22:38.639000,NOR,4,0 days 00:02:05.901000,4.0,1.0,NaT,NaT,0 days 00:00:38.528000,0 days 00:00:35.518000,...,True,McLaren,0 days 00:20:32.738000,2025-03-21 07:38:05.058,1,NaN,False,,False,True
4,0 days 00:24:10.035000,NOR,4,0 days 00:01:31.396000,5.0,1.0,NaT,NaT,0 days 00:00:24.207000,0 days 00:00:27.555000,...,True,McLaren,0 days 00:22:38.639000,2025-03-21 07:40:10.959,1,NaN,False,,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
212,0 days 00:17:06.350000,DOO,7,0 days 00:01:33.129000,2.0,1.0,NaT,NaT,0 days 00:00:24.791000,0 days 00:00:28.114000,...,True,Alpine,0 days 00:15:33.221000,2025-03-21 07:33:05.541,1,NaN,False,,False,True
213,0 days 00:19:08.929000,DOO,7,0 days 00:02:02.579000,3.0,1.0,NaT,NaT,0 days 00:00:31.130000,0 days 00:00:37.759000,...,True,Alpine,0 days 00:17:06.350000,2025-03-21 07:34:38.670,1,NaN,False,,False,True
214,0 days 00:21:15.101000,DOO,7,0 days 00:02:06.172000,4.0,1.0,NaT,NaT,0 days 00:00:33.351000,0 days 00:00:37.366000,...,True,Alpine,0 days 00:19:08.929000,2025-03-21 07:36:41.249,1,NaN,False,,False,True
215,0 days 00:22:47.676000,DOO,7,0 days 00:01:32.575000,5.0,1.0,NaT,NaT,0 days 00:00:24.609000,0 days 00:00:27.945000,...,True,Alpine,0 days 00:21:15.101000,2025-03-21 07:38:47.421,1,NaN,False,,False,True
216,0 days 00:24:48.969000,DOO,7,0 days 00:02:01.293000,6.0,1.0,NaT,0 days 00:24:46.841000,0 days 00:00:33.434000,0 days 00:00:35.993000,...,True,Alpine,0 days 00:22:47.676000,2025-03-21 07:40:19.996,1,NaN,False,,False,False

In [ ]:
import json
import os

import fastf1
import numpy as np
import pandas as pd

import utils

fastf1.Cache.enable_cache("cache")
YEAR = 2025


def events_available(year: int) -> any:
    # get events available for a given year
    data = utils.LatestData(year)
    events = data.get_events()
    return events


events = [
    # 'Australian Grand Prix',
    # 'Chinese Grand Prix',
    # 'Japanese Grand Prix',
    # 'Bahrain Grand Prix',
    # 'Saudi Arabian Grand Prix',
    # 'Miami Grand Prix',
    # "Emilia Romagna Grand Prix",
    # 'Monaco Grand Prix',
    # 'Spanish Grand Prix',
    # 'Canadian Grand Prix',
    # 'Austrian Grand Prix',
    # 'British Grand Prix',
    # 'Belgian Grand Prix',
    # 'Hungarian Grand Prix',
    # 'Dutch Grand Prix',
    # 'Italian Grand Prix',
    # 'Azerbaijan Grand Prix',
    # 'Singapore Grand Prix',
    # 'United States Grand Prix',
    # 'Mexico City Grand Prix',
    # 'São Paulo Grand Prix',
    # 'Las Vegas Grand Prix',
    # 'Qatar Grand Prix',
    # 'Abu Dhabi Grand Prix',

]
sessions = [
    # "Practice 1",
      # "Practice 2",
     "Practice 3",
      # "Qualifying",
       # "Race",
    #"Sprint",
     # "Sprint Qualifying",
]


def sessions_available(year: int, event: str | int) -> any:
    # get sessions available for a given year and event
    event = str(event)
    data = utils.LatestData(year)
    sessions = data.get_sessions(event)
    return sessions


def get_sessions(year, event):
    p1_p2_p3 = ["Practice 1", "Practice 2", "Practice 3"]
    p1_p2_q_r = ["Practice 1", "Practice 2", "Qualifying", "Race"]
    p2_p3_q_r = ["Practice 2", "Practice 3", "Qualifying", "Race"]
    p3_q_r = ["Practice 3", "Qualifying", "Race"]
    p1_q_r = ["Practice 1", "Qualifying", "Race"]
    normal_sessions = [
        "Practice 1",
        "Practice 2",
        "Practice 3",
        "Qualifying",
        "Race",
    ]

    normal_sprint = [
        "Practice 1",
        "Qualifying",
        "Practice 2",
        "Sprint Qualifying",
        "Race",
    ]
    sprint_2022 = [
        "Practice 1",
        "Qualifying",
        "Practice 2",
        "Sprint",
        "Race",
    ]

    sprint_shootout = [
        "Practice 1",
        "Qualifying",
        "Sprint Shootout",
        "Sprint",
        "Race",
    ]
    sprint_shootout_2024 = [
        "Practice 1",
        "Sprint Shootout",
        "Sprint",
        "Qualifying",
        "Race",
    ]

    if year == 2018:
        return normal_sessions
    if year == 2019:
        if event == "Japanese Grand Prix":
            return p1_p2_q_r
        return normal_sessions
    if year == 2020:
        if event == "Styrian Grand Prix":
            return p1_p2_q_r
        if event == "Eifel Grand Prix":
            return p3_q_r
        if event == "Emilia Romagna Grand Prix":
            return p1_q_r

        return normal_sessions
    if year == 2021:
        if (
            event == "British Grand Prix"
            or event == "Italian Grand Prix"
            or event == "São Paulo Grand Prix"
        ):
            return normal_sprint
        else:
            return normal_sessions

    if year == 2022:
        if event == "Pre-Season Test":
            return p1_p2_p3
        if (
            event == "Austrian Grand Prix"
            or event == "Emilia Romagna Grand Prix"
            or event == "São Paulo Grand Prix"
        ):
            return sprint_2022
        else:
            return normal_sessions

    if year == 2023:
        if event == "Pre-Season Testing":
            return p1_p2_p3
        if event == "Hungarian Grand Prix":
            return p2_p3_q_r
        if (
            event == "Austrian Grand Prix"
            or event == "Azerbaijan Grand Prix"
            or event == "Belgium Grand Prix"
            or event == "Qatar Grand Prix"
            or event == "United States Grand Prix"
            or event == "São Paulo Grand Prix"
        ):
            return sprint_shootout
        else:
            return normal_sessions
    if year == 2024:
        if event == "Pre-Season Testing":
            return p1_p2_p3
        if (
            event == "Chinese Grand Prix"
            or event == "Miami Grand Prix"
            or event == "Austrian Grand Prix"
            or event == "United States Grand Prix"
            or event == "São Paulo Grand Prix"
            or event == "Qatar Grand Prix"
        ):
            return sprint_shootout_2024

        return normal_sessions


def session_drivers(year: int, event: str | int, session: str) -> any:
    # get drivers available for a given year, event and session
    import fastf1

    f1session = fastf1.get_session(year, event, session)
    f1session.load(telemetry=True, weather=False, messages=False)

    laps = f1session.laps
    team_colors = utils.team_colors(year)
    # add team_colors dict to laps on Team column
    laps["color"] = laps["Team"].map(team_colors)

    unique_drivers = laps["Driver"].unique()

    drivers = [
        {
            "driver": driver,
            "team": laps[laps.Driver == driver].Team.iloc[0],
        }
        for driver in unique_drivers
    ]

    return {"drivers": drivers}


def session_drivers_list(year: int, event: str | int, session: str) -> any:
    # get drivers available for a given year, event and session
    import fastf1

    f1session = fastf1.get_session(year, event, session)
    f1session.load(telemetry=True, weather=False, messages=False)

    laps = f1session.laps

    unique_drivers = laps["Driver"].unique()

    return list(unique_drivers)


def laps_data(year: int, event: str | int, session: str, driver: str) -> any:
    # get drivers available for a given year, event, and session
    f1session = fastf1.get_session(year, event, session)
    f1session.load(telemetry=False, weather=False, messages=False)
    laps = f1session.laps

    # add team_colors dict to laps on Team column

    # for each driver in drivers, get the Team column from laps and get the color from team_colors dict
    drivers_data = []

    driver_laps = laps.pick_driver(driver)
    driver_laps["LapTime"] = driver_laps["LapTime"].dt.total_seconds()
    # remove rows where LapTime is null
    driver_laps = driver_laps[driver_laps.LapTime.notnull()]

    drivers_data = {
        "time": driver_laps["LapTime"].tolist(),
        "lap": driver_laps["LapNumber"].tolist(),
        "compound": driver_laps["Compound"].tolist(),
    }

    return drivers_data


# # Example usage:
# result = laps_data(2018, "Bahrain", "R", "GAS")
# result


def accCalc(allLapsDriverTelemetry, Nax, Nay, Naz):
    vx = allLapsDriverTelemetry["Speed"] / 3.6
    time_float = allLapsDriverTelemetry["Time"] / np.timedelta64(1, "s")
    dtime = np.gradient(time_float)
    ax = np.gradient(vx) / dtime

    for i in np.arange(1, len(ax) - 1).astype(int):
        if ax[i] > 25:
            ax[i] = ax[i - 1]

    ax_smooth = np.convolve(ax, np.ones((Nax,)) / Nax, mode="same")
    x = allLapsDriverTelemetry["X"]
    y = allLapsDriverTelemetry["Y"]
    z = allLapsDriverTelemetry["Z"]

    dx = np.gradient(x)
    dy = np.gradient(y)
    dz = np.gradient(z)

    theta = np.arctan2(dy, (dx + np.finfo(float).eps))
    theta[0] = theta[1]
    theta_noDiscont = np.unwrap(theta)

    dist = allLapsDriverTelemetry["Distance"]
    ds = np.gradient(dist)
    dtheta = np.gradient(theta_noDiscont)

    for i in np.arange(1, len(dtheta) - 1).astype(int):
        if abs(dtheta[i]) > 0.5:
            dtheta[i] = dtheta[i - 1]

    C = dtheta / (ds + 0.0001)  # To avoid division by 0

    ay = np.square(vx) * C
    indexProblems = np.abs(ay) > 150
    ay[indexProblems] = 0

    ay_smooth = np.convolve(ay, np.ones((Nay,)) / Nay, mode="same")

    # for z
    z_theta = np.arctan2(dz, (dx + np.finfo(float).eps))
    z_theta[0] = z_theta[1]
    z_theta_noDiscont = np.unwrap(z_theta)

    dist = allLapsDriverTelemetry["Distance"]
    ds = np.gradient(dist)
    z_dtheta = np.gradient(z_theta_noDiscont)

    for i in np.arange(1, len(z_dtheta) - 1).astype(int):
        if abs(z_dtheta[i]) > 0.5:
            z_dtheta[i] = z_dtheta[i - 1]

    z_C = z_dtheta / (ds + 0.0001)  # To avoid division by 0

    az = np.square(vx) * z_C
    indexProblems = np.abs(az) > 150
    az[indexProblems] = 0

    az_smooth = np.convolve(az, np.ones((Naz,)) / Naz, mode="same")

    allLapsDriverTelemetry["Ax"] = ax_smooth
    allLapsDriverTelemetry["Ay"] = ay_smooth
    allLapsDriverTelemetry["Az"] = az_smooth

    return allLapsDriverTelemetry


def telemetry_data(year, event, session: str, driver, lap_number):
    f1session = fastf1.get_session(year, event, session)
    f1session.load(telemetry=True, weather=False, messages=False)
    laps = f1session.laps

    driver_laps = laps.pick_driver(driver)
    driver_laps["LapTime"] = driver_laps["LapTime"].dt.total_seconds()

    # get the telemetry for lap_number
    selected_lap = driver_laps[driver_laps.LapNumber == lap_number]

    telemetry = selected_lap.get_telemetry()

    acc_tel = accCalc(telemetry, 3, 9, 9)

    acc_tel["Time"] = acc_tel["Time"].dt.total_seconds()

    laptime = selected_lap.LapTime.values[0]
    # data_key = f"{driver} - Lap {int(lap_number)} - {year} - {session} - [{laptime}]"
    data_key = f"{year}-{event}-{session}-{driver}-{lap_number}"

    acc_tel["DRS"] = acc_tel["DRS"].apply(lambda x: 1 if x in [10, 12, 14] else 0)
    acc_tel["Brake"] = acc_tel["Brake"].apply(lambda x: 1 if x == True else 0)

    telemetry_data = {
        "tel": {
            "time": acc_tel["Time"].tolist(),
            "rpm": acc_tel["RPM"].tolist(),
            "speed": acc_tel["Speed"].tolist(),
            "gear": acc_tel["nGear"].tolist(),
            "throttle": acc_tel["Throttle"].tolist(),
            "brake": acc_tel["Brake"].tolist(),
            "drs": acc_tel["DRS"].tolist(),
            "distance": acc_tel["Distance"].tolist(),
            "rel_distance": acc_tel["RelativeDistance"].tolist(),
            "acc_x": acc_tel["Ax"].tolist(),
            "acc_y": acc_tel["Ay"].tolist(),
            "acc_z": acc_tel["Az"].tolist(),
            "x": acc_tel["X"].tolist(),
            "y": acc_tel["Y"].tolist(),
            "z": acc_tel["Z"].tolist(),
            "dataKey": data_key,
        }
    }
    return telemetry_data

while True:
    try:

        # Your list of events
        events_list = events

        # Loop through each event
        for event in events_list:
            # Get sessions for the current event
            # sessions = sessions_available(YEAR, event)

            # Loop through each session and create a folder within the event folder
            for session in sessions:
                drivers = session_drivers_list(YEAR, event, session)

                for driver in drivers:
                    f1session = fastf1.get_session(YEAR, event, session)
                    f1session.load(telemetry=False, weather=False, messages=False)
                    laps = f1session.laps
                    driver_laps = laps.pick_driver(driver)
                    driver_laps["LapNumber"] = driver_laps["LapNumber"].astype(int)
                    driver_lap_numbers = round(driver_laps["LapNumber"]).tolist()

                    for lap_number in driver_lap_numbers:
                        driver_folder = f"{event}/{session}/{driver}"
                        if not os.path.exists(driver_folder):
                            os.makedirs(driver_folder)

                        try:

                            telemetry = telemetry_data(YEAR, event, session, driver, lap_number)

                            # print(telemetry)

                            # Specify the file path where you want to save the JSON data
                            file_path = f"{driver_folder}/{lap_number}_tel.json"

                            # Save the dictionary to a JSON file
                            with open(file_path, "w") as json_file:
                                json.dump(telemetry, json_file)
                        except:
                            continue


        def session_drivers(year: int, event: str | int, session: str) -> any:
            # get drivers available for a given year, event and session
            import fastf1

            f1session = fastf1.get_session(year, event, session)
            f1session.load(telemetry=True, weather=False, messages=False)

            laps = f1session.laps
            team_colors = utils.team_colors(year)
            # add team_colors dict to laps on Team column
            laps["color"] = laps["Team"].map(team_colors)

            unique_drivers = laps["Driver"].unique()

            drivers = [
                {
                    "driver": driver,
                    "team": laps[laps.Driver == driver].Team.iloc[0],
                }
                for driver in unique_drivers
            ]

            return {"drivers": drivers}


        import json
        import os

        import utils

        # Loop through each event
        for event in events_list:

            # sessions = sessions_available(YEAR, event)

            # sessions = ['Practice 1','Practice 2','Practice 3']

            # Loop through each session and create a folder within the event folder
            for session in sessions:
                drivers = session_drivers(YEAR, event, session)

                import json

                # Specify the file path where you want to save the JSON data
                file_path = f"{event}/{session}/drivers.json"

                # Save the dictionary to a JSON file
                with open(file_path, "w") as json_file:
                    json.dump(drivers, json_file)

                print(f"Dictionary saved to {file_path}")


        def session_drivers_list(year: int, event: str | int, session: str) -> any:
            # get drivers available for a given year, event and session
            import fastf1

            f1session = fastf1.get_session(year, event, session)
            f1session.load(telemetry=True, weather=False, messages=False)

            laps = f1session.laps

            unique_drivers = laps["Driver"].unique()

            return list(unique_drivers)


        def laps_data(year: int, event: str | int, session: str, driver: str) -> any:
            # get drivers available for a given year, event, and session
            f1session = fastf1.get_session(year, event, session)
            f1session.load(telemetry=False, weather=False, messages=False)
            laps = f1session.laps

            # add team_colors dict to laps on Team column

            # for each driver in drivers, get the Team column from laps and get the color from team_colors dict
            drivers_data = []

            driver_laps = laps.pick_driver(driver)
            driver_laps["LapTime"] = driver_laps["LapTime"].dt.total_seconds()
            # remove rows where LapTime is null
            driver_laps = driver_laps[driver_laps.LapTime.notnull()]

            drivers_data = {
                "time": driver_laps["LapTime"].tolist(),
                "lap": driver_laps["LapNumber"].tolist(),
                "compound": driver_laps["Compound"].tolist(),
            }

            return drivers_data


        # Loop through each event
        for event in events_list:

            # # Get sessions for the current event
            # if event == "Qatar Grand Prix":
            #     sessions = ['Practice 1', 'Qualifying', 'Sprint Shootout', 'Sprint', 'Race']
            # else:
            #     sessions = sessions_available(YEAR, event)

            # Loop through each session and create a folder within the event folder
            for session in sessions:
                drivers = session_drivers_list(YEAR, event, session)

                for driver in drivers:
                    # Create a folder for the driver if it doesn't exist
                    driver_folder = f"{event}/{session}/{driver}"
                    if not os.path.exists(driver_folder):
                        os.makedirs(driver_folder)

                    laptimes = laps_data(YEAR, event, session, driver)

                    # Specify the file path where you want to save the JSON data
                    file_path = f"{driver_folder}/laptimes.json"

                    # Save the dictionary to a JSON file
                    with open(file_path, "w") as json_file:
                        json.dump(laptimes, json_file)

                    # print(f"Dictionary saved to {file_path}")








        # corners

        import fastf1
        import os
        import json
        import utils





        def sessions_available(year: int, event: str | int) -> any:
            # get sessions available for a given year and event
            event = str(event)
            data = utils.LatestData(year)
            sessions = data.get_sessions(event)
            return sessions

        for event in events:

            for session in sessions:
                f1session = fastf1.get_session(YEAR, event, session)
                f1session.load()
                circuit_info = f1session.get_circuit_info().corners
                corner_info ={
                    "CornerNumber": circuit_info['Number'].tolist(),
                    "X": circuit_info['X'].tolist(),
                    "Y": circuit_info['Y'].tolist(),
                    "Angle": circuit_info['Angle'].tolist(),
                    "Distance": circuit_info['Distance'].tolist(),
                }

                driver_folder = f"{event}/{session}"
                file_path = f"{event}/{session}/corners.json"
                if not os.path.exists(driver_folder):
                    os.makedirs(driver_folder)
                # Save the dictionary to a JSON file
                with open(file_path, "w") as json_file:
                    json.dump(corner_info, json_file)
        break
    except:
        import time
        time.sleep(5)
        continue



# corner data


from fastf1.req import Cache

PROTO = "https"
HOST = "api.multiviewer.app"
HEADERS = {'User-Agent': f'FastF1/'}


def _make_url(path: str):
    return f"{PROTO}://{HOST}{path}"


def get_circuit(*, year: int, circuit_key: int) :
    """:meta private:
    Request circuit data from the MultiViewer API and return the JSON
    response."""
    url = _make_url(f"/api/v1/circuits/{circuit_key}/{year}")
    response = Cache.requests_get(url, headers=HEADERS)
    if response.status_code != 200:
        _logger.debug(f"[{response.status_code}] {response.content.decode()}")
        return None

    try:
        return response.json()
    except requests.exceptions.JSONDecodeError:
        return None


def get_circuit_info(*, year: int, circuit_key: int):
    """:meta private:
    Load circuit information from the MultiViewer API and convert it into
    as :class:``SessionInfo`` object.

    Args:
        year: The championship year
        circuit_key: The unique circuit key (defined by the F1 livetiming API)
    """
    data = get_circuit(year=year, circuit_key=circuit_key)

    if not data:
        _logger.warning("Failed to load circuit info")
        return None

    ret = list()
    for cat in ('corners', 'marshalLights', 'marshalSectors'):
        rows = list()
        for entry in data[cat]:
            rows.append((
                float(entry.get('trackPosition', {}).get('x', 0.0)),
                float(entry.get('trackPosition', {}).get('y', 0.0)),
                int(entry.get('number', 0)),
                str(entry.get('letter', "")),
                float(entry.get('angle', 0.0)),
                float(entry.get('length',0.0))
            ))
        ret.append(
            pd.DataFrame(
                rows,
                columns=['X', 'Y', 'Number', 'Letter', 'Angle', 'Distance']
            )
        )

    rotation = float(data.get('rotation', 0.0))

    circuit_info =  ret[0]


    return circuit_info

for event in events:
    for session in sessions:
        f1session = fastf1.get_session(YEAR, event, session)
        f1session.load()
        circuit_key = f1session.session_info['Meeting']['Circuit']['Key']
        circuit_info = get_circuit_info(year=YEAR,
                                        circuit_key=circuit_key)
        corner_info ={
            "CornerNumber": circuit_info['Number'].tolist(),
            "X": circuit_info['X'].tolist(),
            "Y": circuit_info['Y'].tolist(),
            "Angle": circuit_info['Angle'].tolist(),
            "Distance": (circuit_info['Distance']/10).tolist(),
        }

        driver_folder = f"{event}/{session}"
        file_path = f"{event}/{session}/corners.json"
        if not os.path.exists(driver_folder):
            os.makedirs(driver_folder)
        # Save the dictionary to a JSON file
        with open(file_path, "w") as json_file:
            json.dump(corner_info, json_file)

In [6]:
events_available(2025)

['Pre-Season Testing']

In [7]:
sessions_available(2025,'Pre-Season Testing' )

['Day 1', 'Day 2', 'Day 3']

In [8]:
year = 2025
event = 'Pre-Season Testing'
session = 'Day 1'

In [11]:
f1session = fastf1.get_testing_session(2025,1,1)
f1session.load(telemetry=True, weather=False, messages=False)

laps = f1session.laps
laps

core           INFO 	Loading data for Pre-Season Testing - Practice 1 [v3.5.0]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...

req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
_api           INFO 	Parsing timing data...

KeyboardInterrupt: